### ISSUE TITLE
Vertical slider support.

### ISSUE THREAD

**Issue by tobiasht** [smofe/input_slider#2]
Please add vertical slider support. I tried wrapping the slider in a Transform.rotate, but unfortunately, there is no way to disable or rotate the text input field. Both of these features would be a good addition to this package.

**Comment by smofe** [comment]
Vertical slider support is a good suggestion, I'll look into it when I have some spare time. Until End of June I'm busy writing my bachelor thesis tho. 

However, I'm not sure if I understand you correctly. If you want to diable the text input field, why don't you simply use [Flutter's native slider](https://api.flutter.dev/flutter/material/Slider-class.html)?

**Comment by tobiasht** [comment]
When I wrote the comment I couldn´t find a way of rotating the label on the slider itself. I have later solved that issue. Anyways the widget you should use to perform the rotation is RotatedBox, not Transform.rotate, my bad.

**Comment by smofe** [comment]
Version 0.3.0 adds the ability to rotate a slider by setting vertical=true. Currently I've implemented it in a way so that only the Sliders gets rotated, but the TextField and optionally the leading widget keep their orientation. The reason is that I don't really see a use case where you want to rotate these widgets as well. 

Does this solve the issue for you? If not, please specify what exactly you are trying to achieve. I'm closing this for now, but feel free to reopen if needed.

**Comment by tobiasht** [comment]
Fantastic!
